name: sentinel
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^2.1.1
  awesome_notifications: 0.7.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#1f1f1f"
  image: "assets/images/logo.png"
#
# dart run flutter_launcher_icons:main
# dart run flutter_native_splash:create

